common/src/main/java/com/dida/common/util/DecimalUtils.kt

fix. 숫자포맷 > DecimalFormat 소수점 에러나는 문제 해결

[DIDA] fix. 숫자포맷 > DecimalFormat 소수점 에러나는 문제 해결

---

data/src/main/java/com/dida/data/api/MainAPIService.kt
data/src/main/java/com/dida/data/mapper/Mapper.kt
data/src/main/java/com/dida/data/model/response/GetBuySellListResponse.kt
data/src/main/java/com/dida/data/model/response/GetTradeHistoryListResponse.kt
domain/src/main/java/com/dida/domain/model/main/TradeHistory.kt
feature/wallet/src/main/java/com/dida/wallet/WalletActionHandler.kt
feature/wallet/src/main/java/com/dida/wallet/WalletViewModel.kt
feature/wallet/src/main/res/layout/fragment_wallet.xml
feature/wallet/src/main/res/layout/holder_wallet_nft_history.xml

- RecyclerView 빈영역을 스크롤할 때 CollapsingToolbar가 접히지않던 문제 해결
- 거래내역 Response에 NftId가 추가된 것 반영 (추후 클릭 이벤트를 위해)

[DIDA] 지갑화면 사소한 에러 수정

---

data/src/main/java/com/dida/data/shareperference/DataStorePreferences.kt
feature/splash/src/main/java/com/dida/splash/SplashViewModel.kt
feature/user-profile/src/main/java/com/dida/user_profile/UserProfileViewModel.kt
presentation/src/main/java/com/dida/android/presentation/views/UserProfileFragment.kt
presentation/src/main/res/navigation/navigation_graph.xml

1. Splash 화면에서 userId 가져오는 API 추가 [ff8bdc6]
2. 내 프로필일 경우 마이페이지로 이동하는 로직 추가 [f77b115]

[DIDA] 내 프로필 클릭 시 마이페이지로 이동

---

feature/home/src/main/java/com/dida/home/HomeViewModel.kt
presentation/src/main/java/com/dida/android/presentation/views/HomeFragment.kt

1. 홈화면API onResume에서 호출하도록 수정 [6b18a9c]
- NFT숨기기 클릭후 홈으로 돌아왔을 떄 반영에 대한 피드백

[DIDA] fix. 홈 > onResume에서 API 호출하도록 수정

---

.idea/deploymentTargetDropDown.xml
common/src/main/java/com/dida/common/util/DecimalBindingAdatper.kt
data/src/main/java/com/dida/data/api/MainAPIService.kt
data/src/main/java/com/dida/data/model/request/PatchNftRemoveRequest.kt
data/src/main/java/com/dida/data/model/request/PostCreateUserRequest.kt
data/src/main/java/com/dida/data/model/request/PostNftMintRequest.kt
data/src/main/java/com/dida/data/repository/MainRepositoryImpl.kt
feature/create-community-input/src/main/res/layout/fragment_create_community_input.xml
feature/create-community/src/main/java/com/dida/create_community/CreateCommunityViewModel.kt
presentation/src/main/AndroidManifest.xml
presentation/src/main/java/com/dida/android/presentation/views/UpdateProfileFragment.kt

- fix. QA > 게시글 작성할 때 제목 두줄이상 입력못하도록 설정
- fix. QA > 게시물 작성 좋아요한 NFT, MY NFT 최신순으로 정렬
- fix. QA > "판매X" 문구를 "NOT SALE"로 변경
- fix. QA > NFT삭제하기 API 수정된 내역 반영
- fix. QA > 프로필 수정 시 카메라 이용 권한 재 설정

[DIDA] 사소한 버그 수정

---

feature/home/src/main/java/com/dida/home/HomeBindingAdapters.kt
feature/hot-seller/src/main/res/layout/fragment_hot_seller.xml
presentation/src/main/java/com/dida/android/presentation/views/HomeFragment.kt

- 핫셀러 > 홈화면에서 핫셀러 아이템 안나오던 문제 해결

[DIDA]fix.핫셀러 > 홈화면에서 핫셀러 아이템 안나오던 문제 해결

---

feature/user-profile/src/main/java/com/dida/user_profile/UserMessageAction.kt
feature/user-profile/src/main/java/com/dida/user_profile/UserProfileViewModel.kt
presentation/src/main/java/com/dida/android/presentation/views/UserProfileFragment.kt

다른사람프로필 > 팔로우,좋아요 Snack bar 추가

[DIDA] feat. 다른사람프로필 > 팔로우,좋아요 Snack bar 추가

---

feature/home/src/main/java/com/dida/home/HomeBindingAdapters.kt
feature/home/src/main/java/com/dida/home/adapter/HotsContainerAdapter.kt
feature/home/src/main/res/layout/holder_hots.xml
feature/home/src/main/res/layout/holder_hots_container.xml

HotItem관련 Recyclerview -> ViewPager2 리팩토링
- 가운데 정렬을 위하여 기존 RecyclerView의 경우 양옆 공백에 대해서 하드코딩이 되어 있음
- ViewPager2의 CompositePageTransformer() 사용

[DIDA] refactor. 홈 HotItems 

---

common/src/main/java/com/dida/common/base/BaseNavigationAction.kt
common/src/main/java/com/dida/common/base/BaseViewModel.kt
presentation/src/main/java/com/dida/android/presentation/views/BaseFragment.kt

멀티 로그인시의 처리
1. 기존 로그인 되어 있는 폰의 경우 앱 사용중일 경우 로그인 해제 & 홈으로 이동
2. 스플래시 화면일 경우 로그인 해제

[DIDA] 멀티 로그인시 처리

---

common/src/main/java/com/dida/common/widget/DefaultSnackBar.kt
common/src/main/res/layout/default_snack_bar.xml
feature/user-profile/src/main/res/layout/fragment_user_profile.xml

토스트 스낵바 > 하단 마진값 수정, 두줄일 경우 디자인 변경(padding, gravity)

[DIDA] refactor. 토스트 스낵바 > 하단 마진값 수정, 두줄일 경우 디자인 변경(padding, gravity)

---

.idea/inspectionProfiles/Project_Default.xml
domain/src/main/java/com/dida/domain/model/main/Follow.kt
feature/user-followed/src/main/java/com/dida/user_followed/UserFollowedViewModel.kt
feature/user-profile/src/main/java/com/dida/user_profile/UserProfileActionHandler.kt
feature/user-profile/src/main/java/com/dida/user_profile/UserProfileNavigationAction.kt
feature/user-profile/src/main/java/com/dida/user_profile/UserProfileViewModel.kt
feature/user-profile/src/main/res/layout/fragment_user_profile.xml
presentation/src/main/java/com/dida/android/presentation/views/UserFollowedFragment.kt
presentation/src/main/java/com/dida/android/presentation/views/UserProfileFragment.kt
presentation/src/main/res/navigation/navigation_graph.xml

1. 팔로워, 팔로잉 클릭에 따른 유저 팔로우 화면 인디케이더 위치 수정

[DIDA] 유저 팔로우 관련 로직 수정

---

common/src/debug/res/drawable/ic_send.xml
common/src/main/res/drawable/ic_send.xml
feature/community-detail/src/main/java/com/dida/community_detail/DetailCommunityBindingAdapters.kt
feature/community-detail/src/main/res/drawable/ic_send_disabled.xml
feature/community-detail/src/main/res/drawable/ic_send_enabled.xml
feature/community-detail/src/main/res/layout/fragment_detail_community.xml

커뮤니티 > 댓글창 공백 시 입력못하도록 수정, 디자인 변경

[DIDA] fix. 커뮤니티 > 댓글창 공백 시 입력못하도록 수정, 디자인 변경

---

common/src/debug/res/drawable/ic_send.xml
common/src/main/res/drawable/custom_surface1_radius10_surface4_width1.xml
common/src/main/res/drawable/custom_surface2_radius6.xml
common/src/main/res/drawable/ic_send.xml
common/src/main/res/values/colors.xml
common/src/main/res/values/styles.xml
feature/community-detail/src/main/java/com/dida/community_detail/DetailCommunityBindingAdapters.kt
feature/community-detail/src/main/res/drawable/ic_send_disabled.xml
feature/community-detail/src/main/res/drawable/ic_send_enabled.xml
feature/community-detail/src/main/res/layout/fragment_detail_community.xml
feature/create-community/src/main/res/layout/holder_create_community_nft.xml
feature/email/src/main/res/layout/fragment_email.xml
feature/mypage/src/main/java/com/dida/mypage/MyPageViewModel.kt
feature/mypage/src/main/java/com/dida/mypage/MypageActionHandler.kt
feature/mypage/src/main/java/com/dida/mypage/MypageNavigationAction.kt
feature/mypage/src/main/res/layout/fragment_mypage.xml
feature/password/src/main/res/layout/dialog_password.xml
presentation/src/main/java/com/dida/android/presentation/views/MyPageFragment.kt
presentation/src/main/res/values/colors.xml

[DIDA] fix. 마이페이지 > 팔로잉 눌렀을 때 팔로우 목록페이지에서 팔로잉탭으로 바로 이동하도록 수정

[DIDA] fix. 마이페이지 > 팔로잉 눌렀을 때 팔로우 목록페이지에서 팔로잉탭으로 바로 이동하도록 수정

---

common/src/debug/res/drawable/ic_send.xml
common/src/main/res/drawable/custom_surface1_radius10_surface4_width1.xml
common/src/main/res/drawable/custom_surface2_radius6.xml
common/src/main/res/drawable/ic_send.xml
common/src/main/res/values/colors.xml
common/src/main/res/values/styles.xml
feature/community-detail/src/main/java/com/dida/community_detail/DetailCommunityBindingAdapters.kt
feature/community-detail/src/main/res/drawable/ic_send_disabled.xml
feature/community-detail/src/main/res/drawable/ic_send_enabled.xml
feature/community-detail/src/main/res/layout/fragment_detail_community.xml
feature/create-community/src/main/res/layout/holder_create_community_nft.xml
feature/email/src/main/res/layout/fragment_email.xml
feature/home/src/main/res/layout/fragment_home.xml
feature/mypage/src/main/java/com/dida/mypage/MyPageViewModel.kt
feature/mypage/src/main/java/com/dida/mypage/MypageActionHandler.kt
feature/mypage/src/main/java/com/dida/mypage/MypageNavigationAction.kt
feature/mypage/src/main/res/layout/fragment_mypage.xml
feature/password/src/main/res/layout/dialog_password.xml
presentation/src/main/java/com/dida/android/presentation/views/MyPageFragment.kt
presentation/src/main/res/values/colors.xml

[DIDA] refactor. 홈 > 홈화면 디자인 수정된 내역 반영, 마진값 수정

[DIDA] refactor. 홈 > 홈화면 디자인 수정된 내역 반영, 마진값 수정

---

feature/add/src/main/res/layout/fragment_create_nft.xml
feature/ai/src/main/java/com/dida/ai/keyword/Keyword.kt
feature/ai/src/main/java/com/dida/ai/keyword/KeywordViewModel.kt
feature/ai/src/main/java/com/dida/ai/keyword/KeywordViewModelDelegate.kt
feature/ai/src/main/java/com/dida/ai/keyword/place/KeywordPlaceViewModel.kt
feature/ai/src/main/java/com/dida/ai/keyword/product/KeywordProductViewModel.kt
feature/ai/src/main/java/com/dida/ai/keyword/style/KeywordStyleViewModel.kt
presentation/src/main/java/com/dida/android/presentation/views/BaseFragment.kt
presentation/src/main/java/com/dida/android/presentation/views/CreateNftFragment.kt
presentation/src/main/java/com/dida/android/presentation/views/KeywordColorFragment.kt
presentation/src/main/java/com/dida/android/presentation/views/KeywordPlaceFragment.kt
presentation/src/main/java/com/dida/android/presentation/views/KeywordProductFragment.kt
presentation/src/main/java/com/dida/android/presentation/views/KeywordStyleFragment.kt
presentation/src/main/java/com/dida/android/presentation/views/ui/KeywordScreen.kt
presentation/src/main/java/com/dida/android/presentation/views/ui/SelectKeyword.kt

해당 내용의 경우 Recomposition을 위주로 살펴봐 주시면 될 것 같습니다.
1. AI 키워드 그리기 > 키워드 클릭시 전체 FlowRow가 Recomposition 되는 현상 [d7c2c31] [a793770]
- FlowRow의 파라미터 값으로 selectedKeyword: String 값을 받고 있었음 (selectedKeyword 상태가 바뀌므로 전체가 Recomposition 되는 문제가 있었습니다.)
2. Base > observeEvent() 수정 [09d62c4]
- 기존의 경우 repeatCreated{ ... } 에서 호출 하고 있었으나 lifecycleScope.launch { ... }로 수정하였습니다.
- repeatCreated{ ... } 는 정지후 재개 이며, 화면간의 롤백 현상이 많은 경우 Event 수신이 불가능하게 됩니다.
3. NFT 생성 > 스크롤뷰로 감싸져 있던 내용 제거 [0338eae]
- Ui가 변경됨에 따라서 NestedScrollView 제거

Refactor. 버그 수정

---

data/src/main/java/com/dida/data/api/HandleApi.kt
data/src/main/java/com/dida/data/di/NetworkModule.kt
data/src/main/java/com/dida/data/interceptor/BearerInterceptor.kt
data/src/main/java/com/dida/data/interceptor/CreateException.kt
data/src/main/java/com/dida/data/model/ErrorResponse.kt
data/src/main/java/com/dida/data/model/ErrorResponseImpl.kt
data/src/main/java/com/dida/data/model/Exceptions.kt

1. 서버 리팩토링에 따른 Exception Handler 수정

[DIDA] Data Exception 관련 코드 수정

---

feature/nickname/src/main/java/com/dida/nickname/NicknameViewModel.kt
feature/nickname/src/main/res/layout/fragment_nickname.xml

1. 닉네임 체크 로직 수정 [e115a17]
- 빈칸일 경우 닉네임 사용 가능 하도록 되던 현상 수정
2. 닉네임 체크 xml 코드 정리 [70f16a9]

[DIDA] 닉네임 체크 화면

---

data/src/main/java/com/dida/data/di/NetworkModule.kt
data/src/main/java/com/dida/data/interceptor/AccessTokenInterceptor.kt
data/src/main/java/com/dida/data/model/main/GetSoldOutResponse.kt
feature/home/src/main/java/com/dida/home/HomeBindingAdapters.kt
feature/home/src/main/java/com/dida/home/HomeViewModel.kt
feature/home/src/main/java/com/dida/home/adapter/HotsContainerAdapter.kt
feature/home/src/main/res/layout/fragment_home.xml
feature/home/src/main/res/layout/holder_soldout.xml
presentation/src/main/java/com/dida/android/presentation/views/HomeFragment.kt

1. SoldOut 매핑 관련 정리 [734c61b]
2. 홈 Hot Item 자동 스크롤 인터렉션 끊기던 내용 수정 [0b4ff4d]
3. 함수 정리

[DIDA] 홈 > QA 및 오류 수정

---

common/src/main/res/drawable/img_arrow_bottom.xml
presentation/src/main/java/com/dida/android/presentation/views/AddFragment.kt

1. DIDA 추천 버블 이미지 사용 -> Compose Canvas로 수정 [906df2b]

[DIDA] fix. NFT 생성 > Bubble Compose로 수정

---

data/src/main/java/com/dida/data/main/DidaApi.kt
feature/email/src/main/java/com/dida/email/EmailViewModel.kt

- 비밀번호 변경 시 암호화 추가, 이메일 인증받기 URL수정

[DIDA]비밀번호 변경 > 비밀번호 변경 시 암호화 추가, 이메일 인증받기 URL수정

---

feature/add/src/main/java/com/dida/add/purpose/AddPurposeViewModel.kt
feature/ai/src/main/java/com/dida/ai/keyword/component/KeywordScreen.kt
feature/splash/src/main/java/com/dida/splash/SplashViewModel.kt
presentation/src/main/java/com/dida/android/presentation/views/KeywordColorFragment.kt
presentation/src/main/java/com/dida/android/presentation/views/KeywordPlaceFragment.kt
presentation/src/main/java/com/dida/android/presentation/views/KeywordProductFragment.kt
presentation/src/main/java/com/dida/android/presentation/views/KeywordStyleFragment.kt

1. AI 키워드 그리기 > 직접 입력 부분 제거(추후 추가되는 영역으로 논의) [aa9fcf7]
2. Splash > 오류 발생시 Splash Screen 제거 안되던 현상 수정 [3d1bb87]
3. NFT 판매 > NFT 생성후 판매 안되던 현상 수정 [94e5b34] [e8089de]
https://github.com/service-dida/Android/assets/84956038/fd4780d8-619b-4bc6-971a-e8daa33b5b95

[DIDA] AI 키워드 그리기 Ui 수정 & Splash 버그 fix & NFT 판매 안되던 현상 수정

---

common/src/main/java/com/dida/common/bindingadapters/ViewBindingAdapters.kt
common/src/main/java/com/dida/common/util/Animation.kt
common/src/main/java/com/dida/common/util/OnDoubleClickListener.kt
feature/nft-detail/src/main/java/com/dida/nft_detail/DetailNftViewModel.kt
feature/nft-detail/src/main/res/layout/fragment_detail_nft.xml
presentation/src/main/java/com/dida/android/presentation/views/DetailNftFragment.kt

1. NFT상세 > 이미지 더블클릭시 좋아요 기능(인스타 처럼)
2. onDoubleClick BindingAdapter 추가
https://github.com/service-dida/Android/assets/84956038/29077c53-6aae-410e-a751-2dd69ba707c2

[DIDA] NFT 상세 > 더블클릭 좋아요 기능 추가

---

common/src/main/res/values/strings.xml
feature/ai/src/main/java/com/dida/ai/keyword/result/KeywordResultImage.kt
feature/ai/src/main/java/com/dida/ai/keyword/result/KeywordResultViewModel.kt
feature/compose/src/main/java/com/dida/compose/utils/Shimmer.kt
presentation/src/main/java/com/dida/android/presentation/views/KeywordResultFragment.kt

1. AI 키워드 그리기 > Shimmer Effect 추가
2. 닫기 버튼 클릭시 팝업
https://github.com/service-dida/Android/assets/84956038/d773166e-7a19-41e9-bc9a-19175d84eb9f
다시 그리기의 경우 이어서 BottomSheet 작업후 PR올리도록 하겠습니다.

[DIDA] AI 키워드 그리기 Shimmer Effect 추가

---

common/src/main/res/drawable/custom_brandlemon_empty_radius10.xml
common/src/main/res/drawable/custom_surface7_empty_radius10.xml
common/src/main/res/drawable/ic_check_24.xml
feature/ai/src/main/java/com/dida/ai/keyword/result/KeywordResultViewModel.kt
feature/ai/src/main/java/com/dida/ai/keyword/result/dialog/AiPictureRestartBottomSheet.kt
feature/ai/src/main/java/com/dida/ai/keyword/result/dialog/AiPictureRestartViewModel.kt
feature/ai/src/main/res/layout/bottom_ai_picture_restart.xml
feature/ai/src/main/res/values/strings.xml
presentation/src/main/java/com/dida/android/presentation/views/KeywordResultFragment.kt

1. AI 키워드 그리기 > 다시 그리기 Botton Sheet 추가
2. Bottom Sheet 클릭에 따른 로직 수정
https://github.com/service-dida/Android/assets/84956038/e4b121c6-4fb9-46b5-9028-d35909821adb

[DIDA] AI 키워드 그리기 > 다시 그리기 바텀시트

---

common/src/main/AndroidManifest.xml
common/src/main/java/com/dida/common/util/VibrateBehavior.kt
feature/password/src/main/java/com/dida/password/PasswordDialog.kt
presentation/src/main/java/com/dida/android/presentation/views/CommunityFragment.kt
presentation/src/main/java/com/dida/android/presentation/views/HomeFragment.kt
presentation/src/main/java/com/dida/android/presentation/views/MyPageFragment.kt
presentation/src/main/java/com/dida/android/presentation/views/SwapFragment.kt
presentation/src/main/java/com/dida/android/presentation/views/UserProfileFragment.kt
presentation/src/main/java/com/dida/android/presentation/views/WalletFragment.kt

1. 새로고침 화면 > Haptic 기능 추가(iOS에서는 RefreshSwipe할 경우 햅틱 발생으로 인하여)
2. 비밀번호 입력 > Vibrate 기능 Common으로 이전(다른 곳에서도 사용할 경우를 대비하여)
~~~kotlin
// 햅틱 이벤트
fun View.performHapticEvent() { }
// Vibrate 이벤트
fun Activity.performVibrate() {}
~~~

[DIDA] 새로고침 화면 Haptic 기능 추가

---

common/src/main/AndroidManifest.xml
common/src/main/java/com/dida/common/util/VibrateBehavior.kt
feature/image-viewer/build.gradle.kts
feature/image-viewer/src/main/res/layout/activity_image_viewer.xml
gradle/didalibs.versions.toml
presentation/src/main/java/com/dida/android/presentation/views/DetailNftFragment.kt

1. NFT 상세 - 이미지 뷰어 > NFT 이미지 Zoom 기능 추가
2. NFT 상세 > 좋아요 햅틱 기능 추가
https://github.com/service-dida/Android/assets/84956038/7e8106eb-8731-4dcd-843c-fefb84eb4338
- Zoom 기능을 위해서 PhotoView 라이브러리 추가했습니다.

[DIDA] NFT 상세 > Zoom 기능 추가

---

common/src/main/res/values/strings.xml
feature/ai/src/main/java/com/dida/ai/keyword/input/KeywordInputViewModel.kt
feature/ai/src/main/res/layout/fragment_keyword_input.xml
feature/ai/src/main/res/values/strings.xml
feature/nickname/src/main/res/layout/fragment_nickname.xml
presentation/src/main/java/com/dida/android/presentation/views/AddFragment.kt
presentation/src/main/java/com/dida/android/presentation/views/KeywordInputFragment.kt
presentation/src/main/res/navigation/navigation_graph.xml

1. AI 키워드 그리기 > 유저 직접 입력하기
2. 닉네임 > Title & 버튼 Background 수정
https://github.com/service-dida/Android/assets/84956038/7818b4fc-6062-4a63-ad80-f349d6411939
- 추후에 조건에 사용할만한 combine 내용 살펴봐도 좋을것 같아요!!
~~~kotlin
val userInput: MutableStateFlow<String> = MutableStateFlow<String>("")
private val _drawEnable: MutableStateFlow<Boolean> = MutableStateFlow<Boolean>(false)
val drawEnable: StateFlow<Boolean> = _drawEnable
.combine(userInput) { _, input ->
input.length >= 10
}.stateIn(
scope = baseViewModelScope,
started = SharingStarted.WhileSubscribed(1000),
initialValue = false
)
~~~

[DIDA] Ai 키워드 그리기 > 유저 직접 입력하기

---

common/src/main/res/layout/fragment_default_dialog.xml
data/src/main/java/com/dida/data/model/Exceptions.kt
feature/ai/src/main/java/com/dida/ai/keyword/result/KeywordResultNavigationAction.kt
feature/ai/src/main/java/com/dida/ai/keyword/result/KeywordResultViewModel.kt
feature/ai/src/main/res/values/strings.xml
presentation/src/main/java/com/dida/android/presentation/views/KeywordResultFragment.kt

1. AI 키워드 그리기 > Exception 정의(달리 리젝, 키워드 매칭X)
- 키워드 매칭 실패
https://github.com/service-dida/Android/assets/84956038/1e2c911c-93ed-4efc-9762-b6fc3bf5b549
- 달리 리젝(사용량 초과)
https://github.com/service-dida/Android/assets/84956038/342efe11-79c1-4b08-afdc-893f9546b4f7

[DIDA] AI 키워드 그리기 > 달리 리젝, 키워드 매칭안될경우 Exception 처리추가

---

README.md
build-logic/convention/src/main/java/com/example/convention/AndroidPresentationConventionPlugin.kt
gradle/didalibs.versions.toml
presentation/src/main/AndroidManifest.xml
presentation/src/main/java/com/dida/android/presentation/di/PresentationApplication.kt
presentation/src/main/java/com/dida/android/presentation/views/KeywordResultFragment.kt

- [DIDA] AdMob > 구글 AdMob광고 implementation 추가
- [DIDA] AdMob > 광고객체 초기화 및 테스트용 광고 Load
- [DIDA] AdMob > ai그리기 완성여부에 따라 광고 한번 더 보여주는 로직 구현
- [DIDA] AdMob > 광고관련 Key값 비공개로 전환

[DIDA] AI생성 시 AdMob 전면배너광고 추가 

---

feature/hot-seller/build.gradle.kts
feature/hot-seller/src/main/java/com/dida/hot_seller/HotSellerMessageAction.kt
feature/hot-seller/src/main/java/com/dida/hot_seller/HotSellerViewModel.kt
feature/hot-seller/src/main/java/com/dida/hot_seller/component/HotSellerItems.kt
feature/hot-seller/src/main/res/layout/fragment_hot_seller.xml
presentation/src/main/java/com/dida/android/presentation/views/HotSellerFragment.kt
presentation/src/main/res/navigation/navigation_graph.xml

1. 핫셀러 더보기
https://github.com/service-dida/Android/assets/84956038/30fce216-00c1-44fe-940f-0f02cad93d18

[DIDA] 핫셀러 더보기

---

feature/nft-detail/src/main/java/com/dida/nft_detail/DetailNftBindingAdapters.kt
feature/nft-detail/src/main/java/com/dida/nft_detail/DetailNftNavigationAction.kt
feature/nft-detail/src/main/java/com/dida/nft_detail/DetailNftViewModel.kt
presentation/src/main/java/com/dida/android/presentation/views/DetailNftFragment.kt

[DIDA] NFT 판매취소 API 구현

---

domain/src/main/java/com/dida/domain/main/model/Swap.kt
feature/swap-history/src/main/java/com/dida/swap/history/SwapHistoryBindingAdapters.kt
feature/swap-history/src/main/res/layout/holder_swap_history.xml
feature/swap/src/main/java/com/dida/swap/SwapViewModel.kt
feature/swap/src/main/java/com/dida/swap/loading/SwapLoadingViewModel.kt
feature/swap/src/main/res/layout/fragment_swap_loading.xml
presentation/src/main/java/com/dida/android/presentation/views/SwapLoadingFragment.kt

1. 스왑 내역 > 스왑 내역 Response에 따른 SwapType 수정
2. 스왑 로띠 > Delay 수정
3. 스왑 > 스왑 ViewModel 코드 정리

[DIDA] 스왑 히스토리

---

domain/src/main/java/com/dida/domain/main/model/Swap.kt
feature/ai/src/main/java/com/dida/ai/keyword/component/KeywordMoreScreen.kt
feature/ai/src/main/java/com/dida/ai/keyword/component/KeywordScreen.kt
feature/ai/src/main/java/com/dida/ai/keyword/component/NextButton.kt
feature/ai/src/main/java/com/dida/ai/keyword/component/SelectKeyword.kt
feature/compose/src/main/java/com/dida/compose/common/DidaText.kt
presentation/src/main/java/com/dida/android/presentation/views/AddFragment.kt
presentation/src/main/java/com/dida/android/presentation/views/BlockFragment.kt
presentation/src/main/java/com/dida/android/presentation/views/CreateCommunityFragment.kt
presentation/src/main/java/com/dida/android/presentation/views/LoginMainFragment.kt
presentation/src/main/java/com/dida/android/presentation/views/SettingsFragment.kt
presentation/src/main/java/com/dida/android/presentation/views/UserFollowedFragment.kt

1. 기존 Text Composable -> DidaTextComposable
~~~kotlin
val DidaBoldTypography = DidaTypography.h3
val DidaSemiBoldTypography = DidaTypography.subtitle1
val DidaMediumTypography = DidaTypography.body1
val DidaRegularTypography = DidaTypography.caption
// header
DidaBoldText()
// subtitle
DidaSemiBoldText()
// body
DidaMediumText()
// caption
DidaRegulartText()
~~~

[DIDA] Compose > Text Composable 

---

common/src/main/res/values/strings.xml
data/src/main/java/com/dida/data/main/DidaApi.kt
data/src/main/java/com/dida/data/main/MainRepositoryImpl.kt
data/src/main/java/com/dida/data/model/additional/AdditionalMapper.kt
data/src/main/java/com/dida/data/model/additional/GetAppVersionResponse.kt
domain/src/main/java/com/dida/domain/main/MainRepository.kt
domain/src/main/java/com/dida/domain/main/model/AppVersion.kt
domain/src/main/java/com/dida/domain/usecase/AppVersionUseCase.kt
feature/splash/src/main/java/com/dida/splash/SplashViewModel.kt
presentation/src/main/java/com/dida/android/presentation/views/SplashFragment.kt
presentation/src/main/res/values/strings.xml

1. 앱 버전 체크 API 추가
2. 강제 업데이트 팝업 추가
https://github.com/service-dida/Android/assets/84956038/5ebfc3e8-71ab-45df-86f9-9076253d690c
1. 앱 강제 업데이트 로직
- 업데이트 : 스토어 이동
- 거절 : 앱 종료

[DIDA] 앱 버전 체크 로직

---

feature/settings/src/main/java/com/dida/settings/SettingsViewModel.kt

[DIDA] 설정 > 미 구현 목록 제거

---

domain/src/main/java/com/dida/domain/main/model/ReEmailType.kt
feature/email/src/main/res/layout/fragment_email.xml
feature/email/src/main/res/values/strings.xml
presentation/src/main/java/com/dida/android/presentation/views/AddFragment.kt
presentation/src/main/java/com/dida/android/presentation/views/EmailFragment.kt
presentation/src/main/java/com/dida/android/presentation/views/MyPageFragment.kt
presentation/src/main/java/com/dida/android/presentation/views/SettingsFragment.kt
presentation/src/main/java/com/dida/android/presentation/views/SwapFragment.kt
presentation/src/main/res/navigation/navigation_graph.xml

1. 이메일 > 버그 수정(defaultValue에 대해서 지정안되어 있던 현상)
2. 이메일 > ToolBar 추가

[DIDA] 비밀번호 설정 > 비밀번호 설정 오류 수정 및 ToolBar 추가
